version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Ensure the correct Dockerfile is used
    container_name: django_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: "backend.settings"

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - ./backend/.env

    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
